yasm/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks",
                                       :registrations      => "registrations" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resources :users do
      resources :sites do
        resources :pages
        resources :comments
        post 'rate'
      end
      resources :pictures, only: [:index, :create, :update, :destroy]
    end

    resources :tags do
      collection do
        get 'current'
      end
    end

    root :to => 'sites#home'

    get '/search', to: "search#search", as: "search"
    post '/users/:user_id/pictures/update', to: 'pictures#update', as: 'update_picture'
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"),
                 constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :all
  match '', to: redirect("/#{I18n.default_locale}"), via: :all
end

yasm/app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  def self.update(user, params)
    picture = user.pictures.find_by public_id: params["public_id"]
    picture["public_id"] = Cloudinary::Uploader.upload(params["new_url"], :format => 'png')["public_id"]
    picture.save
  end
end

yasm/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_user

  def index
    @pictures = @user.pictures.all.to_a
  end

  def create
    @picture = @user.pictures.create(:public_id => params[:public_id])
  end

  def update
    Picture.update(@user, params)
  end

  def destroy
    @picture = @user.pictures.find(params[:id])
    @picture.destroy
    redirect_to user_pictures_path
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end
end

yasm/app/helpers/pictures_helper.rb
module PicturesHelper
end

yasm/app/views/pictures/index.html.erb
<div class="container" style="padding-top: 60px">
  <div class="row pictures">
    <% @pictures.each do |picture| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <div class="caption">
            <p class="pull-right" rel="tooltip">
              <a onclick="return launchEditor($(this).closest('.thumbnail').find('img'));"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
              <a data-method="delete" href="<%= user_picture_path picture.user, picture %>">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
              </a>
            </p>
            <div class="clearfix"></div>
          </div>
          <%= cl_image_tag picture.public_id, :id => picture.public_id, :class => "img-responsive", "data-toggle" => "modal", "data-target" => "#pictureModal" %>
        </div>
      </div>
    <% end %>
  </div>
  <span id="update-path" url="<%= update_picture_path %>"></span>
  
  <!-- Modal -->
  <div class="modal fade" id="pictureModal" tabindex="-1" role="dialog" aria-labelledby="pictureModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <img class="img-responsive" alt="One second...">
        </div>
      </div>
    </div>
  </div>

</div>